game:
  name: 'tic_tac_toe'
  actions: 9
  observation_shape: [3, 3, 3]

model:
  channels: 32
  blocks: 5
  # Save a checkpoint every N steps.
  checkpoint_freq: 10

optimizer:
  learning_rate: 0.01
  weight_decay: 0.001
  # Train the model when there are N newly generated states.
  frequency: 1000
  # How many states to store in the replay buffer.
  replay_buffer_size: 10000
  # How many times to reuse each state in the replay buffer.
  replay_buffer_reuse: 4
  # How many states to learn from per batch.
  batch_size: 500

mcts:
  # PUCT exploration constant.
  c_puct: 1.25
  # How many MCTS simulations to run for each step.
  simulation_count: 400
  discount_factor: 1.
  dirichlet:
    # What dirichlet noise alpha to use.
    alpha: 1.0
    # What dirichlet noise epsilon to use.
    epsilon: 0.25
