name: Sphinx Docs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install doxygen
      run: sudo apt-get -y -qq install doxygen graphviz libprotobuf-dev protobuf-compiler
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install breathe Sphinx sphinx-copybutton sphinx_rtd_theme
        pip install gym pyyaml tensorboard zmq zstandard
        pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Build & Commit Docs
      run: |
        export CMAKE_PREFIX_PATH=`python3 -c 'import torch; print(torch.__path__[0] + "/share/cmake/Torch")'`
        python setup.py build_docs
        git fetch origin
        git checkout gh-pages
        rm -rf docs
        cp -r build/temp.linux-x86_64-3.8/docs/sphinx docs/
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git add docs
        git commit -m 'rebuild docs' -a || true
        git push origin gh-pages || true